<div id="css-navigation-bar-links-right"><!--
                 --><span id="css-link-about">About</span><!--
                 --><span id="css-link-archive">Archive</span><!--
                 --><span id="css-link-contact">Contact</span><!--
             --></div><!--
         --></div><!--
         --><div id="css-navigation-bar-section-right"><!--
             --><i class="fa fa-github"></i><!--
             --><i class="fa fa-youtube-square"></i><!--
             --><i class="fa fa-facebook-official"></i><!--
             --><i class="fa fa-google-plus-square"></i><!--
         --></div><!--
         --><div class="css-navigation-bar-segment css-segment-right"></div><!--
     --></div><!--
 --></div>